# Generated by Django 3.2.9 on 2022-06-04 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='email_subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=150)),
                ('expertise', models.CharField(max_length=1000)),
                ('trainer_pic', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=1000)),
                ('file_mainpic', models.FileField(upload_to='')),
                ('Description', models.TextField()),
                ('price', models.IntegerField()),
                ('week', models.CharField(max_length=150)),
                ('pic1', models.FileField(upload_to='')),
                ('Date', models.TimeField()),
                ('location', models.CharField(max_length=300)),
                ('trainer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers_profile', to='yogashala.trainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('top_content', models.TextField()),
                ('content', models.TextField()),
                ('important_notes', models.TextField()),
                ('main_pic1', models.FileField(upload_to='')),
                ('pic1', models.FileField(upload_to='')),
                ('pic2', models.FileField(upload_to='')),
                ('Date', models.DateField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogashala.category')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
