# Generated by Django 4.2.6 on 2023-12-09 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("yogashala", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcart",
            name="Email",
            field=models.EmailField(default="anupthatal2@gmail.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemcart",
            name="completed",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
        migrations.AddField(
            model_name="itemcart",
            name="contact",
            field=models.CharField(default=9869111406),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemcart",
            name="country",
            field=models.CharField(default="Nepal", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemcart",
            name="course_purchase_date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="itemcart",
            name="name",
            field=models.CharField(default="Anup Thatal", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemcart",
            name="paid",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
        migrations.AddField(
            model_name="itemcart",
            name="payment",
            field=models.CharField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemcart",
            name="price",
            field=models.CharField(default="20"),
            preserve_default=False,
        ),
    ]
