# Generated by Django 4.2.6 on 2023-12-09 04:59

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "yogashala",
            "0002_itemcart_email_itemcart_completed_itemcart_contact_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemcart",
            name="Email",
        ),
        migrations.RemoveField(
            model_name="itemcart",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="itemcart",
            name="country",
        ),
        migrations.RemoveField(
            model_name="itemcart",
            name="course_purchase_date",
        ),
        migrations.RemoveField(
            model_name="itemcart",
            name="name",
        ),
        migrations.RemoveField(
            model_name="itemcart",
            name="paid",
        ),
        migrations.RemoveField(
            model_name="itemcart",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="itemcart",
            name="price",
        ),
        migrations.AddField(
            model_name="itemcart",
            name="customer_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itemcart",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="itemcart",
            name="is_purchased",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="itemcart",
            name="purchase_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="itemcart",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="itemcart",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="itemcart",
            name="contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="itemcart",
            name="items",
            field=models.ManyToManyField(related_name="carts", to="yogashala.course"),
        ),
    ]
