# Generated by Django 3.2.9 on 2022-06-05 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yogashala', '0002_alter_blog_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100000)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogashala.blog')),
            ],
        ),
    ]
