# Generated by Django 3.2.9 on 2022-07-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogashala', '0003_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
