# Generated by Django 4.2.6 on 2023-12-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "yogashala",
            "0004_rename_customer_details_itemcart_any_sepcial_request_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcart",
            name="country",
            field=models.CharField(default="Nepal"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemcart",
            name="location",
            field=models.CharField(default="Kapan"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemcart",
            name="name",
            field=models.CharField(default="Anup Thatal"),
            preserve_default=False,
        ),
    ]
