# Generated by Django 4.2.6 on 2023-12-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yogashala", "0005_itemcart_country_alter_itemcart_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemcart",
            name="unique_id",
        ),
        migrations.AlterField(
            model_name="itemcart",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
