# Generated by Django 4.2.6 on 2023-12-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yogashala", "0006_remove_itemcart_unique_id_alter_itemcart_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcart",
            name="quantity",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="itemcart",
            name="items",
            field=models.ManyToManyField(related_name="course", to="yogashala.course"),
        ),
    ]
