# Generated by Django 4.2.6 on 2023-12-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yogashala", "0007_itemcart_quantity_alter_itemcart_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcart",
            name="Email",
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name="itemcart",
            name="contact",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="itemcart",
            name="country",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="itemcart",
            name="location",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="itemcart",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
