# Generated by Django 4.2.6 on 2023-12-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yogashala", "0008_alter_itemcart_email_alter_itemcart_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="is_trainer",
            field=models.BooleanField(default=False),
        ),
    ]
