# Generated by Django 4.2.6 on 2023-12-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yogashala", "0009_trainer_is_trainer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="country",
            field=models.CharField(max_length=100),
        ),
    ]
