# Generated by Django 4.2.6 on 2023-12-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yogashala", "0010_alter_trainer_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="location",
            field=models.CharField(max_length=300),
        ),
    ]
