# Generated by Django 4.2.6 on 2023-12-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yogashala", "0011_alter_trainer_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainer",
            name="title",
        ),
        migrations.AddField(
            model_name="trainer",
            name="Email",
            field=models.EmailField(default="anupthatal2@gmail.com", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainer",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
